exclude: ^comparisons/single_cell_analysis/aide_qr.py$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        args: [sempipes]
        additional_dependencies:
          - skrub==0.6.1
          - plotly==6.3.0
          - networkx==3.5
          - litellm==1.76.1
          - jupyter==1.1.1
          - lightgbm==4.6.0
          - xgboost==3.0.5
          - torch==2.8.0
          - transformers==4.57.1
          - catboost==1.2.8
          - dataclasses-json==0.6.7
          - interpret==0.2.7
          - sentence-transformers==5.1.2
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: ["--config-file", "mypy.ini"]
        additional_dependencies:
          - skrub==0.6.1
          - plotly==6.3.0
          - networkx==3.5
          - litellm==1.76.1
          - jupyter==1.1.1
          - lightgbm==4.6.0
          - xgboost==3.0.5